language: python

python:
    - "2.7"

before_install:

    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - wget http://cran.rstudio.com/src/base/R-3/R-3.1.1.tar.gz
    - tar xvf R-3.1.1.tar.gz
    - cd R-3.1.1
    - make && make install
    - pip install rpy2

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
    - pip install scipy

script:
    - cd DevelopingRelease/WinnowDevel/Tests
    - python winnowdevel_test_suite.py
    - cd ..
    - cd ../DemonstrateDevel/Tests
    - python demonstratedevel_test_suite.py