#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Application:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'available': 'bool',
            'checkpointable': 'bool',
            'defaultMaxRunTime': 'str',
            'defaultMemoryPerNode': 'str',
            'defaultNodeCount': 'str',
            'defaultProcessorsPerNode': 'str',
            'defaultQueue': 'str',
            'deploymentPath': 'str',
            'deploymentSystem': 'str',
            'executionSystem': 'str',
            'executionType': 'str',
            'helpURI': 'str',
            'id': 'str',
            'icon': 'str',
            'inputs': 'list[ApplicationInput]',
            'label': 'str',
            'lastModified': 'datetime',
            'longDescription': 'str',
            'modules': 'list[str]',
            'name': 'str',
            'ontology': 'list[str]',
            'outputs': 'list[ApplicationOutput]',
            'parallelism': 'str',
            'parameters': 'list[ApplicationParameter]',
            'public': 'bool',
            'revision': 'int',
            'shortDescription': 'str',
            'tags': 'list[str]',
            'templatePath': 'str',
            'testPath': 'str',
            'uuid': 'str',
            'version': 'str'

        }


        #Whether the application is available.
        self.available = None # bool
        #Whether the application supports checkpointing.
        self.checkpointable = None # bool
        #The max execution time that should be used if none is given in a job description. Ignore if the system does not support schedulers.
        self.defaultMaxRunTime = None # str
        #The default memory in GB to pass to the scheduler if none is given in the job description. This must be less than the max memory parameter in the target queue definition.
        self.defaultMemoryPerNode = None # str
        #The number of nodes that should be used if none is given in a job description. Ignore if the system does not support schedulers.
        self.defaultNodeCount = None # str
        #The number of processors to pass to the scheduler if none are given in the job description. This must be 1 if the app is serial.
        self.defaultProcessorsPerNode = None # str
        #The queue on the execution system that should be used if none is given in a job description. Ignore if the system does not support schedulers.
        self.defaultQueue = None # str
        #The location in the user's default storage system containing the application wrapper and dependencies.
        self.deploymentPath = None # str
        #The system id of the storage system where this app should run.
        self.deploymentSystem = None # str
        #The system id of the execution system where this app should run.
        self.executionSystem = None # str
        #The execution type of the application. If you're unsure, it's probably HPC.
        self.executionType = None # str
        #The URL where users can go for more information about the app.
        self.helpURI = None # str
        #Unique id of this app. Comprised of the app name-version.
        self.id = None # str
        #The icon to associate with this app.
        self.icon = None # str
        #The inputs files for this application. 
        self.inputs = None # list[ApplicationInput]
        #The label to use when generating forms.
        self.label = None # str
        #The date this application was last modified in ISO 8601 format.
        self.lastModified = None # datetime
        #The full text description of this input to use when generating forms.
        self.longDescription = None # str
        #An array of modules to load prior to the execution of the application.
        self.modules = None # list[str]
        #The name of the application. The name does not have to be unique, but the combination of name and version does.
        self.name = None # str
        #An array of ontology values describing this application.
        self.ontology = None # list[str]
        #The outputs files for this application. 
        self.outputs = None # list[ApplicationOutput]
        #The parallelism type of the application. If you're unsure, it's probably SERIAL.
        self.parallelism = None # str
        #The inputs parameters for this application. 
        self.parameters = None # list[ApplicationParameter]
        #Whether the application is public or private.
        self.public = None # bool
        #The number of times this application has been revised.
        self.revision = None # int
        #The short description of this application.
        self.shortDescription = None # str
        #An array of tags related to this application.
        self.tags = None # list[str]
        #The path to the wrapper script relative to the deploymentPath.
        self.templatePath = None # str
        #The path to the test script relative to the deploymentPath.
        self.testPath = None # str
        #The UUID of this application. UUID are 36 alphanumeric string.
        self.uuid = None # str
        #The version of the application in #.#.# format. While the version does not need to be unique, the combination of name and version does have to be unique.
        self.version = None # str
        
