#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class ApplicationSummary:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'id': 'str',
            'executionSystem': 'str',
            'lastModified': 'datetime',
            'name': 'str',
            'public': 'bool',
            'revision': 'int',
            'shortDescription': 'str',
            'version': 'str'

        }


        #Unique id of this app. Comprised of the app name-version.
        self.id = None # str
        #The system id of the execution system where this app should run.
        self.executionSystem = None # str
        #The date this application was last modified in ISO 8601 format.
        self.lastModified = None # datetime
        #The name of the application. The name does not have to be unique, but the combination of name and version does.
        self.name = None # str
        #Whether the application is public or private.
        self.public = None # bool
        #The number of times this application has been revised.
        self.revision = None # int
        #The short description of this application.
        self.shortDescription = None # str
        #The version of the application in #.#.# format. While the version does not need to be unique, the combination of name and version does have to be unique.
        self.version = None # str
        
