#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class ApplicationParameterValue:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'defaultValue': 'str',
            'enum_values': 'list[str]',
            'order': 'int',
            'required': 'bool',
            'type': 'str',
            'validator': 'str',
            'visible': 'bool'

        }


        #The default value for this parameter. The type will be determined by the value.type field.
        self.defaultValue = None # str
        #An array of enumerated object values.
        self.enum_values = None # list[str]
        #The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.
        self.order = None # int
        #Is this parameter required? If visible is false, this must be true.
        self.required = None # bool
        #The type of this parameter value.
        self.type = None # str
        #The regular expression used to validate this parameter value. For enumerations, separate values with |
        self.validator = None # str
        #Should this parameter be visible? If not, there must be a default and it will be required.
        self.visible = None # bool
        
