#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class InternalUser:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'city': 'str',
            'country': 'str',
            'department': 'str',
            'email': 'str',
            'fax': 'str',
            'firstName': 'str',
            'gender': 'str',
            'institution': 'str',
            'lastName': 'str',
            'phone': 'str',
            'position': 'str',
            'researchArea': 'str',
            'state': 'str',
            'status': 'str',
            'username': 'str'

        }


        #The api user's city.
        self.city = None # str
        #The api user's country.
        self.country = None # str
        #The api user's institutional department.
        self.department = None # str
        #The api user's unique email address.
        self.email = None # str
        #The api user's fax number.
        self.fax = None # str
        #The api user's first name.
        self.firstName = None # str
        #The api user's gender. male or female.
        self.gender = None # str
        #The api user's home institution
        self.institution = None # str
        #The api user's last name.
        self.lastName = None # str
        #The api user's phone number.
        self.phone = None # str
        #The api user's position of employment.
        self.position = None # str
        #The api user's primary area of research.
        self.researchArea = None # str
        #The api user's state.
        self.state = None # str
        #The api user's status. active or deleted.
        self.status = None # str
        #The api user's unique username.
        self.username = None # str
        
