#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class LoginConfig:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'auth': 'UserCredential',
            'host': 'str',
            'port': 'int',
            'protocol': 'String'

        }


        #The default authentication credential used for this system.
        self.auth = None # UserCredential
        #The hostname or ip address of the submission server
        self.host = None # str
        #The port number of the submission server.
        self.port = None # int
        #The protocol used to authenticate to the submission server.
        self.protocol = None # String
        
