#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Notification:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'associatedUuid': 'str',
            'attempts': 'int',
            'created': 'datetime',
            'lastSent': 'datetime',
            'owner': 'str',
            'persistent': 'bool',
            'responseCode': 'int',
            'success': 'bool',
            'url': 'str',
            'uuid': 'str'

        }


        #UUID of resource to whome the event applies.
        self.associatedUuid = None # str
        #The number of times this notification has been attempted to be fulfilled.
        self.attempts = None # int
        #A timestamp indicating when this notification was created in the notification store.
        self.created = None # datetime
        #A timestamp indicating the last time this notification was sent.
        self.lastSent = None # datetime
        #The API user who owns this notification.
        self.owner = None # str
        #Whether this notification should stay active after it fires the first time.
        self.persistent = None # bool
        #The response code from POSTing to the url or sending an email.
        self.responseCode = None # int
        #Whether this notification was sent successfully.
        self.success = None # bool
        #The url or email address that will be notified of the event.
        self.url = None # str
        #The UUID for this notification.
        self.uuid = None # str
        
