#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class PostIt:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'created': 'datetime',
            'creator': 'str',
            'expires': 'datetime',
            'internalUsername': 'str',
            'method': 'str',
            'postit': 'str',
            'remainingUses': 'int',
            'url': 'str'

        }


        #The creation date in ISO 8601 format.
        self.created = None # datetime
        #The api user who made the PostIt creation request.
        self.creator = None # str
        #The expiration date in ISO 8601 format.
        self.expires = None # datetime
        #The username of the internal user attached to this PostIt.
        self.internalUsername = None # str
        #The url that will be invoked when the PostIt is redeemed.
        self.method = None # str
        #The PostIt nonce.
        self.postit = None # str
        #The number of invocations remaining on this token. 
        self.remainingUses = None # int
        #The url that will be invoked when the PostIt is redeemed.
        self.url = None # str
        
