#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class RemoteFile:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'format': 'str',
            'lastModified': 'datetime',
            'length': 'int',
            'mimeType': 'str',
            'name': 'str',
            'owner': 'str',
            'path': 'str',
            'permissions': 'str',
            'type': 'str'

        }


        #The file type of the file.
        self.format = None # str
        #The date this file was last modified in ISO 8601 format.
        self.lastModified = None # datetime
        #The length of the file/folder.
        self.length = None # int
        #The mime type of the file/folder. If unknown, it defaults to application/binary.
        self.mimeType = None # str
        #The name of the file/folder.
        self.name = None # str
        #Local username of the owner.
        self.owner = None # str
        #The absolute path to the file/folder.
        self.path = None # str
        #The permission of the invoking user on the file/folder.
        self.permissions = None # str
        #Whether it is a file or folder.
        self.type = None # str
        
