#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class StorageConfig:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'auth': 'UserCredential',
            'homeDir': 'str',
            'host': 'str',
            'port': 'int',
            'protocol': 'String',
            'resource': 'str',
            'rootDir': 'str',
            'zone': 'str'

        }


        #The default authentication credential used for this system.
        self.auth = None # UserCredential
        #The path on the remote system to use as the home directory for all API requests. For cases where the home directory should be dynamically defined, the ${USERNAME} token can be included in the homeDir value to represent the username of the authenticated user. ex. /home/${USERNAME}.
        self.homeDir = None # str
        #The hostname or ip address of the storage server
        self.host = None # str
        #The port number of the storage server.
        self.port = None # int
        #The protocol used to authenticate to the storage server.
        self.protocol = None # String
        #The name of the target resource when defining an IRODS system.
        self.resource = None # str
        #The path on the remote system to use as the root for all API requests.
        self.rootDir = None # str
        #The name of the zone when defining an IRODS system.
        self.zone = None # str
        
