#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class System:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'default': 'bool',
            'description': 'str',
            'id': 'str',
            'lastModified': 'datetime',
            'name': 'str',
            'public': 'bool',
            'site': 'str',
            'status': 'str',
            'storage': 'StorageConfig',
            'type': 'str'

        }


        #Is the system the default for the authenticated user?
        self.default = None # bool
        #Verbose description of this system.
        self.description = None # str
        #Unique identifier for this system.
        self.id = None # str
        #The date this system was last modified in ISO 8601 format.
        self.lastModified = None # datetime
        #Common name for this system.
        self.name = None # str
        #Is the system publicly available?
        self.public = None # bool
        #The site associated with this system.
        self.site = None # str
        #The status of this system. Systems must be in UP status to be used.
        self.status = None # str
        #The storage config defining how to connect to this system for data staging.
        self.storage = None # StorageConfig
        #The type of this system.
        self.type = None # str
        
